# Generated by Django 3.2.2 on 2021-05-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0005_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='active',
            field=models.BooleanField(default=True, help_text='User will get near by kitchen on the active address only'),
        ),
    ]
