# Generated by Django 3.2.2 on 2021-05-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0006_useraddress_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='zipcode',
            new_name='pincode',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='address_type',
            field=models.CharField(choices=[('HOME', 'Home'), ('WORK', 'Work'), ('HOTEL', 'Hotel'), ('OTHER', 'OTHER')], default=('HOME', 'Home'), max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='complete_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='landmark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
