# Generated by Django 3.2.2 on 2021-05-27 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0008_auto_20210526_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='recommended_by',
        ),
    ]
