# Generated by Django 3.2.2 on 2021-05-21 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='total_likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
