# Generated by Django 3.2.2 on 2021-05-21 01:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0002_kitchen_total_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchen',
            name='total_likes',
        ),
        migrations.RemoveField(
            model_name='kitchen',
            name='total_order_placed',
        ),
        migrations.AddField(
            model_name='item',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='Kitchen_Item', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='total_order_placed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
