# Generated by Django 3.2.2 on 2021-05-21 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0003_auto_20210521_0645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchen',
            name='kitchen_owner',
        ),
        migrations.AddField(
            model_name='kitchen',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Select user who is vendor.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='likes',
            field=models.ManyToManyField(related_name='Kitchen_Item', to=settings.AUTH_USER_MODEL),
        ),
    ]
