# Generated by Django 3.2.2 on 2021-05-22 16:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0004_auto_20210521_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='Kitchen_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='Kitchen_Item', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='veg',
            field=models.BooleanField(default=False),
        ),
    ]
