# Generated by Django 3.2.2 on 2021-05-25 01:44

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('restaurant', '0005_auto_20210522_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_name',
        ),
        migrations.AddField(
            model_name='category',
            name='category_name',
            field=taggit.managers.TaggableManager(help_text='Enter Category for an Item. Create only if the category is not pre-present.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='kitchencuisine',
            name='cuisine_names',
            field=taggit.managers.TaggableManager(help_text="What's the kitchen main cuisines? Not more than 10.", through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
