# Generated by Django 3.2.2 on 2021-05-27 18:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0007_remove_item_special_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='Kitchen_Item', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='Kitchen_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
