# Generated by Django 3.2.2 on 2021-06-01 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_auto_20210528_0018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kitchen',
            old_name='name',
            new_name='kitchen_name',
        ),
    ]
