# Generated by Django 3.2.2 on 2021-06-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_alter_kitchencuisine_cuisine_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchen',
            name='email',
        ),
        migrations.RemoveField(
            model_name='kitchen',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='kitchen',
            name='kitchen_status',
            field=models.CharField(blank=True, choices=[('OPEN', 'open'), ('BUSY', 'busy'), ('CLOSE', 'close')], max_length=100, null=True),
        ),
    ]
