# Generated by Django 3.2.2 on 2021-06-10 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0013_alter_kitchen_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Select user who is vendor.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
