# Generated by Django 3.2.2 on 2021-06-10 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_alter_kitchen_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchen',
            name='likes',
        ),
    ]
