# Generated by Django 3.2.2 on 2021-06-10 19:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0015_remove_kitchen_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='Kitchen_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
