# Generated by Django 3.2.2 on 2021-06-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_kitchen_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen',
            name='kitchen_status',
            field=models.CharField(blank=True, choices=[('OPEN', 'open'), ('BUSY', 'busy'), ('CLOSE', 'close')], default=('OPEN', 'open'), max_length=100, null=True),
        ),
    ]
