# Generated by Django 3.2.2 on 2021-06-12 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0019_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='kitchen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.kitchen'),
        ),
    ]
