# Generated by Django 3.2.2 on 2021-06-15 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0020_category_kitchen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchencuisine',
            name='kitchen',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='restaurant.kitchen'),
        ),
    ]
