# Generated by Django 3.2.2 on 2021-06-16 21:25

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('restaurant', '0022_auto_20210616_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchencuisine',
            name='cuisine_names',
            field=taggit.managers.TaggableManager(blank=True, help_text="What's the kitchen main cuisines? Not more than 5.", through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
