# Generated by Django 3.2.2 on 2021-05-27 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0009_auto_20210528_0018'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moredata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refer_Earn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=12)),
                ('total_refer_money', models.CharField(blank=True, help_text='50 rs redeemed at each order.', max_length=1000, null=True)),
                ('redeemed_money', models.CharField(blank=True, max_length=1000, null=True)),
                ('my_recommended_users', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refer_earn', to='userinfo.profile')),
                ('recommended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
