# Generated by Django 3.2.2 on 2021-05-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moredata', '0003_alter_refer_earn_my_recommended_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refer_earn',
            name='redeemed_money',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='refer_earn',
            name='total_refer_money',
            field=models.IntegerField(blank=True, default=0, help_text='50 rs redeemed at each order.', null=True),
        ),
    ]
