# Generated by Django 3.2.2 on 2021-06-10 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_alter_kitchencuisine_cuisine_names'),
        ('moredata', '0004_auto_20210528_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verified_Kitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verify', models.BooleanField(default=False)),
                ('kitchen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verf_kitc', to='restaurant.kitchen')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
