# Generated by Django 3.2.2 on 2021-06-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_orderhistory_checksum'),
        ('moredata', '0007_auto_20210616_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refer_earn',
            old_name='total_refer_money',
            new_name='total_ref_money',
        ),
        migrations.AddField(
            model_name='refer_earn',
            name='orders_redeemed_on',
            field=models.ManyToManyField(blank=True, to='order.Order'),
        ),
    ]
