# Generated by Django 3.2.2 on 2021-06-17 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_orderhistory_checksum'),
        ('userinfo', '0010_auto_20210618_0206'),
        ('account', '0003_auto_20210618_0206'),
        ('moredata', '0009_auto_20210618_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='refer_earn_vendor',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refer_earn', to='userinfo.vendorprofile'),
        ),
        migrations.AddField(
            model_name='refer_earn_vendor',
            name='recommended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_by_vendor', to='account.vendor'),
        ),
        migrations.AddField(
            model_name='refer_earn_customer',
            name='my_recommended_users',
            field=models.ManyToManyField(blank=True, related_name='my_recommended_customer', to='account.Customer'),
        ),
        migrations.AddField(
            model_name='refer_earn_customer',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refer_earn', to='userinfo.customerprofile'),
        ),
        migrations.AddField(
            model_name='refer_earn_customer',
            name='recommended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_by_customer', to='account.customer'),
        ),
        migrations.AddField(
            model_name='refer_earn_customer',
            name='redeem_on_orders',
            field=models.ManyToManyField(blank=True, to='order.Order'),
        ),
    ]
