# Generated by Django 3.2.2 on 2021-06-18 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210618_1439'),
        ('moredata', '0010_auto_20210618_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Refer_Earn_Vendor',
            name='recommended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_by_vendor', to='account.vendor'),
        ),
        migrations.AlterField(
            model_name='Refer_Earn_Vendor',
            name='my_recommended_users',
            field=models.ManyToManyField(blank=True, related_name='my_recommended_vendor', to='account.Vendor'),
        ),
        migrations.AlterField(
            model_name='Refer_Earn_Customer',
            name='recommended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_by_customer', to='account.customer'),
        ),
        migrations.AlterField(
            model_name='Refer_Earn_Customer',
            name='my_recommended_users',
            field=models.ManyToManyField(blank=True, related_name='my_recommended_customer', to='account.Customer'),
        ),
    ]
