# Generated by Django 3.2.2 on 2021-06-18 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moredata', '0014_auto_20210618_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refer_earn_customer',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='refer_earn_vendor',
            name='profile',
        ),
        migrations.AddField(
            model_name='refer_earn_customer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refer_earn_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refer_earn_vendor',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refer_earn_vendor', to=settings.AUTH_USER_MODEL),
        ),
    ]
