# Generated by Django 3.2.2 on 2021-05-21 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='transaction_id',
            field=models.CharField(default=0, max_length=150),
        ),
    ]
