# Generated by Django 3.2.2 on 2021-05-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210521_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='review',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
