# Generated by Django 3.2.2 on 2021-06-16 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210616_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='updated_at',
        ),
    ]
