# Generated by Django 3.2.2 on 2021-06-16 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_orderhistory_succes_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='complete',
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='complete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='future_date',
            field=models.DateField(blank=True, help_text='Date selected for the future order', null=True),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='future_time',
            field=models.TimeField(blank=True, help_text='Time Slot selected for the future order delivery', null=True),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='is_future',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='succes_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
