# Generated by Django 3.2.2 on 2021-06-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20210617_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='for_future',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, help_text='Date selected for the future order', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_time',
            field=models.TimeField(blank=True, help_text='Time Slot selected for the future order delivery', null=True),
        ),
        migrations.DeleteModel(
            name='FutureOrder',
        ),
    ]
