# Generated by Django 3.2.2 on 2021-06-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_orderhistory_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_time',
            new_name='order_slot_from',
        ),
        migrations.AddField(
            model_name='order',
            name='order_slot_to',
            field=models.TimeField(blank=True, help_text='Time Slot selected for the future order delivery', null=True),
        ),
    ]
