# Generated by Django 3.2.2 on 2021-06-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20210617_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
