# Generated by Django 3.2.2 on 2021-06-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_orderhistory_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='checksum',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
